### ISSUE TITLE
Autofilter crashes  in AutoFilter::activate due to unconnected ports

### ISSUE THREAD

**Issue by x42** [moddevices/caps-lv2#11]
jalv activates a plugin before connecting ports.

src/jalv.c  first calls `lilv_instance_activate()` and later `jalv_backend_activate()` which calls `jack_activate()`.  The jack-callback calls `lilv_instance_connect_port()`.

caps-lv2 `AutoFilter::activate()` calls `f=getport(2)/fs, Q=getport(3);`  which segfaults

**Comment by falkTX** [comment]
This has been handled quite some time ago. I think you have a very old build of this repo.
See https://github.com/moddevices/caps-lv2/blob/master/Descriptor.h#L175
