### ISSUE TITLE
New version on glibc requires uses exp10f instead of pow10f

### ISSUE THREAD

**Issue by guysoft** [moddevices/caps-lv2#16]
Current workaround is to run  
```
sed 's/pow10f/exp10f/g' dsp/v4f_IIR2.h -i
```

**Comment by trebmuh** [comment]
Duplicate of https://github.com/moddevices/caps-lv2/pull/15

**Comment by guysoft** [comment]
Should I close? can move the workaround there

**Comment by trebmuh** [comment]
It depends of the moddevices people. The purpose of my last message was to be informational.
