### ISSUE TITLE
Is this repo dead or maintained?

### ISSUE THREAD

**Issue by trebmuh** [moddevices/caps-lv2#20]
@ricardocrudo @jesseverhage @jkbd : I'm pinging the 3 of you because I don't understand who is in charge with this repo.

There are a few important PR which are waiting for someone from mod to be merged. Do you consider maintaining this repo or would someone from the linuxaudio community be fine to take it over?

**Comment by falkTX** [comment]
I am very interested as well.
If no one from mod wants to manage the project, I will fork it and keep it maintained myself.

**Comment by BramGiesen** [comment]
We do still want to maintain this repo but it’s true that there has been a lack of attention here. I will be able to merge to PR’s tomorrow
