### ISSUE TITLE
Compilation Error w/ GCC 6.2.1

### ISSUE THREAD

**Issue by jazzyeagle** [moddevices/caps-lv2#9]
Having issues compiling using a PKGBUILD script from the Arch User Repository (AUR) @  https://aur.archlinux.org/packages/caps-lv2-git/ .  I cloned it and attempted to make directly; same error.  The Package maintainer believes there is some sort of incompatibility w/ GCC > 6.1 (using 6.2.1 on my machine).

[jazzyeagle@JazzyPuter caps-lv2]$ make
make -C plugins/mod-caps-AmpVTS.lv2
make[1]: Entering directory '/home/jazzyeagle/Downloads/caps-lv2/plugins/mod-caps-AmpVTS.lv2'
g++ -MM -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. ../../Amp.cc ../../ToneStack.cc ../../dsp/polynomials.cc interface.cc > .depend
g++ ../../Amp.cc -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. -o ../../Amp.o -c
g++ ../../ToneStack.cc -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. -o ../../ToneStack.o -c
g++ ../../dsp/polynomials.cc -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. -o ../../dsp/polynomials.o -c
g++ interface.cc -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. -o interface.o -c
g++ ../../Amp.o ../../ToneStack.o ../../dsp/polynomials.o interface.o -Wl,--strip-all -shared -Wl,--no-undefined -o AmpVTS.so
make[1]: Leaving directory '/home/jazzyeagle/Downloads/caps-lv2/plugins/mod-caps-AmpVTS.lv2'
make -C plugins/mod-caps-AutoFilter.lv2
make[1]: Entering directory '/home/jazzyeagle/Downloads/caps-lv2/plugins/mod-caps-AutoFilter.lv2'
g++ -MM -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. ../../AutoFilter.cc ../../dsp/polynomials.cc interface.cc > .depend
g++ ../../AutoFilter.cc -O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -I../.. -o ../../AutoFilter.o -c
../../AutoFilter.cc: In member function ‘void AutoFilter::cycle(uint)’:
../../AutoFilter.cc:72:35: error: call of overloaded ‘div(uint&, uint&)’ is ambiguous
  div_t qr = div (frames, blocksize);
                                   ^
In file included from /usr/include/c++/6.2.1/cstdlib:75:0,
                 from /usr/include/c++/6.2.1/stdlib.h:36,
                 from ../../basics.h:41,
                 from ../../AutoFilter.cc:31:
/usr/include/stdlib.h:749:14: note: candidate: div_t div(int, int)
 extern div_t div (int __numer, int __denom)
              ^~~
In file included from /usr/include/c++/6.2.1/stdlib.h:36:0,
                 from ../../basics.h:41,
                 from ../../AutoFilter.cc:31:
/usr/include/c++/6.2.1/cstdlib:233:3: note: candidate: lldiv_t __gnu_cxx::div(long long int, long long int)
   div(long long __n, long long __d)
   ^~~
/usr/include/c++/6.2.1/cstdlib:175:3: note: candidate: ldiv_t std::div(long int, long int)
   div(long __i, long __j) { return ldiv(__i, __j); }
   ^~~
make[1]: *** [Makefile:42: ../../AutoFilter.o] Error 1
make[1]: Leaving directory '/home/jazzyeagle/Downloads/caps-lv2/plugins/mod-caps-AutoFilter.lv2'
make: *** [Makefile:9: build] Error 2

**Comment by falkTX** [comment]
Try this:
```
div_t qr = div ((int)frames, (int)blocksize);
```

**Comment by jazzyeagle** [comment]
Thank you.  That fixed the issue!!  If you could please make the update to the repo and let me know when it's done, I'll put a note on the AUR so folks know that it's been fixed upstream.  Thanks!!

**Comment by falkTX** [comment]
Thanks for confirming, pushing the fix now.
